### ISSUE TITLE
Seemingly random render and input lag

### ISSUE THREAD

**Issue by williamleven** [sidusIO/sediment#69]
After some time connected to a docking station, the computer would randomly about 4 times a minute experience extrema lag spikes, with rendering and input devices freezing or stuttering for a few seconds. Spikes vary from lasting upwards of 5 seconds to only a few milliseconds and behaviors have been observed to be worse while running heavy applications.

# Debugging
1. CPU usage seems to be moderate with slight spikes in conjunction with the lag spikes. 
2. Several short lives processes running `/bin/sh -c echo 13b1 0bdc > /sys/bus/usb/drivers/brcmfmac/new_id` seems to coincide with the lag-spikes
3. These processes are child processes of systemd-dbus
4. Inspecting the systemd-dbus debug log (`/usr/lib/systemd/systemd-udevd -D`) we can confirm that these executions are triggered by the `/usr/lib/udev/rules.d/30-linksys-ae1200.rules` rule.
5. Checking the kernel event log (`udevadm monitor`) we can see that this rules is triggered intermittently by the creation of virtual networks `/devices/virtual/net/veth3...`
6. Names of these networks seems to correspond with docker network devices, they can be listed with `systemctl list-units | grep sys-devices-virtual-net-veth`
7. Stopping all running docker containers and deleting their networks stops the kernel event activity and also remedies the lag spikes

# Upstream
No upstream project seems to have any issues logged for this problem.

# TODO

- [ ] 1. Investigate if podman is effected
- [ ] 2. Create reproducible example
- [ ] 3. Report to upstream
- [ ] 4. Disable or modify the `/usr/lib/udev/rules.d/30-linksys-ae1200.rules` rule.
